# Generated by Django 3.1 on 2024-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user_name', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('environment', models.IntegerField(choices=[('1', '开发环境'), ('2', '测试环境'), ('3', '线上环境')], verbose_name='环境')),
                ('age', models.IntegerField(max_length=100, null=True, verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[('1', '男'), ('2', '女')], verbose_name='性别')),
                ('interest', models.CharField(max_length=100, null=True, verbose_name='爱好')),
                ('motto', models.TextField(null=True, verbose_name='座右铭')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_by', models.CharField(default='sys', max_length=10, null=True, verbose_name='创建人')),
            ],
            options={
                'db_table': 'create_user',
            },
        ),
    ]
