# Generated by Django 3.1 on 2024-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusertable',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
