# Generated by Django 3.1 on 2024-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240401_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createusertable',
            name='age',
        ),
        migrations.AddField(
            model_name='createusertable',
            name='birthdate',
            field=models.CharField(max_length=30, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='createusertable',
            name='is_marital',
            field=models.BooleanField(null=True, verbose_name='是否结婚'),
        ),
        migrations.AddField(
            model_name='createusertable',
            name='personality_label',
            field=models.CharField(max_length=100, null=True, verbose_name='个性标签'),
        ),
        migrations.AddField(
            model_name='createusertable',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='体重'),
        ),
    ]
