# Generated by Django 3.1 on 2024-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240401_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusertable',
            name='environment',
            field=models.CharField(max_length=10, verbose_name='环境'),
        ),
    ]
