# Generated by Django 3.1 on 2024-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240401_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('resolve', models.CharField(default='否', max_length=50, verbose_name='是否解决')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_by', models.CharField(default='sys', max_length=10, null=True, verbose_name='创建人')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
